# Generated by Django 4.0 on 2022-01-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIF', models.CharField(max_length=50)),
                ('NOMBRE', models.CharField(max_length=250)),
                ('APPELIDO', models.CharField(max_length=250)),
                ('EDAD', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tEye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('NIF', models.CharField(max_length=50)),
                ('CONSULTA', models.DateTimeField()),
                ('OD_ESFERA', models.DecimalField(decimal_places=15, max_digits=30)),
                ('OD_CILINDRO', models.DecimalField(decimal_places=15, max_digits=30)),
                ('OD_ADICION', models.DecimalField(decimal_places=15, max_digits=30)),
                ('OD_AGUDEZA', models.DecimalField(decimal_places=15, max_digits=30)),
                ('OI_ESFERA', models.DecimalField(decimal_places=15, max_digits=30)),
                ('OI_CILINDRO', models.DecimalField(decimal_places=15, max_digits=30)),
                ('OI_ADICION', models.DecimalField(decimal_places=15, max_digits=30)),
                ('OI_AGUDEZA', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
