# Generated by Django 4.0 on 2022-01-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tClient',
            fields=[
                ('NIF', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=250)),
                ('APPELIDO', models.CharField(max_length=250)),
                ('EDAD', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tEye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RevisionOcularApp.tclient')),
            ],
        ),
    ]
