# Generated by Django 4.0 on 2022-01-12 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RevisionOcularApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teye',
            name='CONSULTA',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teye',
            name='OD_ADICION',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='teye',
            name='OD_AGUDEZA',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='teye',
            name='OD_CILINDRO',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='teye',
            name='OD_ESFERA',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='teye',
            name='OI_ADICION',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='teye',
            name='OI_AGUDEZA',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='teye',
            name='OI_CILINDRO',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='teye',
            name='OI_ESFERA',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='tclient',
            name='NIF',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teye',
            name='NIF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RevisionOcularApp.tclient'),
        ),
    ]
