# Generated by Django 4.0 on 2022-01-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevisionOcularApp', '0002_teye_consulta_teye_od_adicion_teye_od_agudeza_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tclient',
            old_name='APPELIDO',
            new_name='APELLIDO',
        ),
    ]
