# Generated by Django 4.0 on 2022-01-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevisionOcularApp', '0003_rename_appelido_tclient_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teye',
            name='OD_ADICION',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='teye',
            name='OD_AGUDEZA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='teye',
            name='OD_CILINDRO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='teye',
            name='OD_ESFERA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='teye',
            name='OI_ADICION',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='teye',
            name='OI_AGUDEZA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='teye',
            name='OI_CILINDRO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='teye',
            name='OI_ESFERA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
