# Generated by Django 4.0 on 2022-01-14 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RevisionOcularApp', '0004_alter_teye_od_adicion_alter_teye_od_agudeza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teye',
            name='CONSULTA',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
